# Generated by Django 3.0.4 on 2020-04-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(max_length=200)),
                ('dress_color', models.CharField(max_length=200)),
                ('dress_detail', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('materail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devcart.Material')),
            ],
        ),
    ]
