# Generated by Django 3.0.4 on 2020-04-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='materail',
            new_name='material',
        ),
    ]
