# Generated by Django 3.0.4 on 2020-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcart', '0002_auto_20200412_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='material',
            name='dress_image',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
    ]
